name: mms_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  another_flushbar: ^1.10.20
  flutter_svg: ^0.22.0
  pinput: ^1.1.0
  dotted_border: ^2.0.0+1
  flutter_screenutil: ^5.0.1+2
  flutter_staggered_grid_view: ^0.6.0
  intl: ^0.17.0
  grouped_list: ^4.1.0
  file_picker: ^4.3.2
  modal_bottom_sheet: ^2.0.0
  share_plus: ^3.0.4
  percent_indicator: ^4.0.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  blur: ^3.0.0
  flutter_keyboard_visibility: ^5.1.1
  keyboard_attachable: ^2.1.0

dev_dependencies:
  flutter_native_splash: ^1.2.1

flutter_native_splash:
  color: "#FFF1E2"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/ctg/
    - assets/